name: snapfi_mobile_challenge_pokedex_roveri
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.3.2

dependencies:
  cached_network_image: ^3.3.1
  dio: ^5.4.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9
  logger: ^2.2.0
  provider: ^6.1.2

dev_dependencies:
  bloc_test: ^9.1.7
  dart_code_metrics: ^5.7.6
  flutter_test:
    sdk: flutter
  http_mock_adapter: ^0.6.1
  mocktail: ^1.0.3
  mocktail_image_network: ^1.1.0
  test: ^1.24.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          style: normal
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
