name: snapfi_mobile_challenge_pokedex_roveri
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.1.0

dependencies:
  cached_network_image: ^3.2.3
  dio: ^5.3.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_screenutil: ^5.9.0-beta
  flutter_svg: ^2.0.7
  logger: ^1.4.0
  provider: ^6.0.5

dev_dependencies:
  bloc_test: ^9.1.4
  dart_code_metrics: ^5.7.6
  flutter_test:
    sdk: flutter
  http_mock_adapter: ^0.4.4
  mocktail: ^1.0.0 
  mocktail_image_network: ^1.0.0
  test: ^1.24.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          style: normal
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
