name: snapfi_mobile_challenge_pokedex_roveri
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  cached_network_image: ^3.2.3
  dio: ^5.1.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.6
  logger: ^1.3.0
  provider: ^6.0.5

dev_dependencies:
  bloc_test: ^9.1.3
  dart_code_metrics: ^5.7.4
  http_mock_adapter: ^0.4.4
  mocktail: ^0.3.0
  test: ^1.24.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          style: normal
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
